spring:
  application:
    name: stan_blog
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      connect-timeout: 3000
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/stan_blog?useUnicode=true&character_set_server=utf8mb4
    charset: utf8mb4
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: stan_Hikari_Pool
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mail:
    host: smtp.gmail.com # Change to actual SMTP server
    port: 587 # Common SMTP port
    username: username@example.com # Replace with actual email
    password: password # Replace with actual password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          timeout: 30000
          connectiontimeout: 30000
          writetimeout: 30000

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs
jwt:
  # 256 digits secret key, remember to replace before go live to prod
  secret:
    access: 482B4D6251655468576D597133743677397A24432646294A404E635266556A58
    refresh: 38782F413F4428472B4B6250645367566B597033733676397924422645294840
  # millis time to expire, by default access expire time 15 mins and refresh expire time 24 hours
  expire:
    # access: 900000
    access: 86400000
    refresh: 864000000
security-context:
  enable: true
mybatis-plus:
  global-config:
    banner: false
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
mail:
  mail-from: username@example.com
storage:
  baseDir: uploads
  publicBaseUrl: /files
